name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Decode google-services.json
        env:
          MAPS_SECRET: ${{ secrets.MAPS_SECRET }}
        run: echo $MAPS_SECRET > ./maps.properties

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_velobike.apk
          path: app/build/outputs/apk/debug/app-debug.apk
